# docker-compose.prod.yml

services:

  db:
    env_file:
      - ./backend/.prod.env
    ports:
      - "5432:5432"
    volumes:
      - todo_prod_data:/var/lib/postgresql/data
    networks:
      - todo-prod-net


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: >
      sh -c "python manage.py migrate && 
      python manage.py collectstatic --noinput &&  
      gunicorn todo_project.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./backend/.prod.env
    environment:
      - DJANGO_SETTINGS_MODULE=todo_project.settings.prod
    depends_on:
      - db
    networks:
      - todo-prod-net
    volumes:
      - django_static:/code/staticfiles


  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    networks:
      - todo-prod-net
    ports:
      - "8080:80"
    volumes:
      - django_static:/static:ro
      - ./nginx/nginx.container.conf:/etc/nginx/conf.d/default.conf:ro


volumes:
  todo_prod_data:
  django_static:


networks:
  todo-prod-net:
    driver: bridge