from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from .views import TodoViewSet
from django.urls import path, include

router = DefaultRouter()
router.register(r"todo_list", TodoViewSet, basename="todo-list")

urlpatterns = [
    path("", include(router.urls)),
    # ---------- Endpoints JWT ----------
    # POST to get access/refresh tokens.
    path('login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # POST to refresh the access token.
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # POST to verify a token.
    path('verify/', TokenVerifyView.as_view(), name='token_verify'),

    # todo_list urls (generated by router)
    # *router.urls
]